project:
  type: website

execute:
  freeze: true

website:
  title: "Stats & bats"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ThierryO
      - icon: linkedin
        href: https://www.linkedin.com/in/thierryonkelinx/
  image: image/androidify.png
  cookie-consent: false

format:
  html:
    theme: flatly
    css: styles.css

editor: source
