---
title: Review of the ReadRPA software
author: Thierry Onkelinx
date: '2017-09-26'
slug: readrpa
categories: ["bats", "tool review"]
tags: ["peersonic", "bat detector", "review"]
banner: ''
description: ''
images: []
menu: ''
---

# Introduction

The default way to download recordings from a [Peersonic](http://peersonic.co.uk) bat detector is to connect the detector via a USB cable to the computer and copy them to the computer. The file transfer rate is quite low. In case you have to copy 100 to 200 files, this is OKish. But copying a full SD card takes half a day. In case you have a set-up with multiple detectors, this becomes a nightmare.

Peersonic bat detectors use a custom [file allocation table](https://en.wikipedia.org/wiki/File_Allocation_Table) called BatFAT. Therefore it can not be read on computers. Recently, Peersonic made the [ReadRPA software](http://peersonic.co.uk/technical-support/) freely available on their website. This is Windows software which makes a fast copy from all the files on the SD card to the computer. Peersonic has tested it on Windows 8 - 10 / 64 bit. Today I've tested the ReadRPA software on a full SD card: 1559 recordings totaling 16 GB. 

# Installation

I booted my laptop with Windows 7. Then I downloaded the software and the manual from the [Peersonic website](http://peersonic.co.uk/technical-support/). The download is a zip file with the installation files. Unpack them and run `setup.exe`. Note that you have to right click on the file and then select `Run as administrator`. I failed to do that the first time and then the installation hangs. The manual states that a desktop short cut would be created. This was not the case. It is easy to manually create the short cut to the `start.bat` in the software folder (`C:\Program Files\Peersonuc\Readrpa\` by default).

# Copying the files

First we need to extract the SD card from the RPA bat detector. That is easy with the [IP67 enclosure](../../07/peersonic-ip67). The SD card is located underneath the display. I used a pair of tweezers. First to push the SD card so that the spring-loaded slot releases the card. And then to grab and extract the SD card. After the slot ejected the SD card, it still is covered by the display and hard to reach for my fingers.

The next step is to plug the SD card into the computer. Warning: in case the computer asks you to format the card: **DON'T DO THAT**. You will loose all recordings. Just note which drive letter is assigned to the SD card.

Now it is time to start the `ReadRPA` software. Don't be intimidated by the DOS windows it opens. You will have to enter the command manually, but it is short and the software displays an example. The example command is `readrpa E: C:\temp\out.zip`. `readrpa` is the software. `E:` is the drive letter of the SD card, so you might need to replace that with the drive letter that was assigned to the SD card. `C:\temp\out.zip` is the name of the drive, the path and the file name where you want the recordings to be copied to. Hit `enter` can the process starts. All recordings will be copied to the single zip file that you specified. It is fast: 16 GB took about 20 minutes instead of half a day over the USB connection.

The file names in the recordings are changed. The new format is `wav####_yyyy_mm_dd__HH_MM_SS.wav`. The `####` part is the number of the file, starting at 0. The `yyyy_mm_dd__HH_MM_SS` part is the date and time of the recording. The information on the peak frequency is no longer available in the file name.

Once the files are copied, you can remove the SD card from the computer and put it back into the bat detector. There you can delete the recordings from the SD card.

# Conclusion

`readrpa` is a very useful tool to copy a large amount of files from the SD card to the computer. A set of SD cards for each detector is handy in case you don't want to copy the files in the field.
