project:
  output-dir: ../output
  type: website

execute:
  freeze: auto

website:
  title: "Stats & bats"
  page-navigation: true
  back-to-top-navigation: true
  site-url: https://www.muscardinus.be
  repo-url: https://github.com/ThierryO/my_blog
  repo-subdir: source
  issue-url: https://github.com/ThierryO/my_blog/issues
  repo-actions: [source, edit, issue]
  body-footer: >
    [![](/media/kofi.svg){fig-alt="Support me on Ko-Fi"}](https://ko-fi.com/R5R063BR7)
  image: /media/androidify.png
  open-graph:
    image: /media/androidify.png
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ThierryO
      - icon: mastodon
        href: https://fosstodon.org/%40ThierryO
        rel: me
      - icon: linkedin
        href: https://www.linkedin.com/in/thierryonkelinx/
    logo: /media/androidify.png

format:
  html:
    theme: flatly
    css: styles.css

editor: source
