name: On PR, build the site and save the result to an artifact

on:
  pull_request

jobs:
  build-and-save:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout (tutorials)
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.62.2'
          # extended: true

      - name: Build
        run: hugo

      - name: Archive built site to an artifact
        uses: actions/upload-artifact@v2
        with:
          name: pr-${{ env.PR_NUMBER }}-blog-website
          path: public
        env:
          PR_NUMBER: ${{ github.event.number }}
